---

- name: "1.1.6.1 | AUDIT | Ensure separate partition exists for /var/log/audit"
  block:
      - name: "1.1.6.1 | AUDIT | Ensure separate partition exists for /var/log/audit | Warn if partition is absent"
        debug:
            msg: "Warning!! /var/log/audit does not exist, which is not STIG compliant. This is a manual task remediate"
        when: "'/var/log/audit' not in mount_names"

      - name: "1.1.6.1 | AUDIT | Ensure separate partition exists for /var/log/audit | Warn Count"
        set_fact:
            control_number: "{{ control_number }} + [ 'rule_1.1.6.1' ]"
            warn_count: "{{ warn_count | int + 1 }}"
        when: "'/var/log/audit' not in mount_names"
  when:
      - rhel8cis_rule_1_1_6_1
  tags:
      - level2-server
      - level2-workstation
      - automated
      - audit
      - mounts
      - rule_1.1.6.1

# skips if mount is absent
- name: |
          "1.1.6.2 | PATCH | Ensure noexec option set on /var/log/audit partition"
          "1.1.6.3 | PATCH | Ensure nodev option set on /var/log/audit partition"
          "1.1.6.4 | PATCH | Ensure nosuid option set on /var/log/audit partition"
  mount:
      name: /var/log/audit
      src: "{{ item.device }}"
      fstype: "{{ item.fstype }}"
      state: present
      opts: defaults,{% if rhel8cis_rule_1_1_6_2 %}noexec,{% endif %}{% if rhel8cis_rule_1_1_6_3 %}nodev,{% endif %}{% if rhel8cis_rule_1_1_6_4 %}nosuid{% endif %}
  notify: change_requires_reboot
  with_items:
      - "{{ ansible_mounts }}"
  loop_control:
      label: "{{ item.device }}"
  when:
      - "'/var/log/audit' in mount_names"
      - item.mount == "/var/log/audit"
      - rhel8cis_rule_1_1_6_2 or
        rhel8cis_rule_1_1_6_3 or
        rhel8cis_rule_1_1_6_4
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - mounts
      - skip_ansible_lint
      - rule_1.1.6.2
      - rule_1.1.6.3
      - rule_1.1.6.4
