---

- name: "1.1.7.1 | AUDIT | Ensure separate partition exists for /home"
  block:
      - name: "1.1.7.1 | AUDIT | Ensure separate partition exists for /home | Warn if partition is absent"
        debug:
            msg: "Warning!! /home does not exist, which is not STIG compliant. This is a manual task remediate"
        when: "'/home' not in mount_names"

      - name: "1.1.7.1 | AUDIT | Ensure separate partition exists for /home | Warn Count"
        set_fact:
            control_number: "{{ control_number }} + [ 'rule_1.1.7.1' ]"
            warn_count: "{{ warn_count | int + 1 }}"
        when: "'/home' not in mount_names"
  when:
      - rhel8cis_rule_1_1_7_1
  tags:
      - level2-server
      - level2-workstation
      - automated
      - audit
      - mounts
      - rule_1.1.7.1
      - skip_ansible_lint

# skips if mount is absent
- name: |
    "1.1.7.2 | PATCH | Ensure nodev option set on /home partition
     1.1.7.3 | PATCH | Ensure nosuid option set on /home partition
     1.1.7.4 | PATCH | Ensure usrquota option set on /home partition
     1.1.7.5 | PATCH | Ensure grpquota option set on /home partition"
  mount:
      name: /home
      src: "{{ item.device }}"
      fstype: "{{ item.fstype }}"
      state: present
      opts: defaults,{% if rhel8cis_rule_1_1_7_2 %}nodev,{% endif %}{% if rhel8cis_rule_1_1_7_3 %}nosuid,{% endif %}{% if rhel8cis_rule_1_1_7_4 %}usrquota,{% endif %}{% if rhel8cis_rule_1_1_7_5 %}grpquota{% endif %}
  notify: change_requires_reboot
  with_items:
      - "{{ ansible_mounts }}"
  loop_control:
      label: "{{ item.device }}"
  when:
      - "'/home' in mount_names"
      - item.mount == "/home"
      - rhel8cis_rule_1_1_7_2 or
        rhel8cis_rule_1_1_7_3 or
        rhel8cis_rule_1_1_7_4 or
        rhel8cis_rule_1_1_7_5
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - mounts
      - rule_1.1.7.2
      - rule_1.1.7.3
      - rule_1.1.7.4
      - skip_ansible_lint
