---

- name: "1.1.4.1 | AUDIT | Ensure separate partition exists for /var/tmp"
  block:
      - name: "1.1.4.1 | AUDIT | Ensure separate partition exists for /var/tmp | Warn if partition is absent"
        debug:
            msg: "Warning!! /var/tmp does not exist, which is not STIG compliant. This is a manual task remediate"
        when: "'/var/tmp' not in mount_names"

      - name: "1.1.4.1 | AUDIT | Ensure separate partition exists for /var/tmp | Warn Count"
        set_fact:
            control_number: "{{ control_number }} + [ 'rule_1.1.4.1' ]"
            warn_count: "{{ warn_count | int + 1 }}"
        when: "'/var/tmp' not in mount_names"
  when:
      - rhel8cis_rule_1_1_4_1
  tags:
      - level2-server
      - level2-workstation
      - automated
      - audit
      - mounts
      - rule_1.1.4.1

# skips if mount is absent
- name: |
          "1.1.4.2 | PATCH | Ensure noexec option set on /var/tmp partition"
          "1.1.4.3 | PATCH | Ensure nosuid option set on /var/tmp partition"
          "1.1.4.4 | PATCH | Ensure nodev option set on /var/tmp partition"
  mount:
      name: /var/tmp
      src: "{{ item.device }}"
      fstype: "{{ item.fstype }}"
      state: present
      opts: defaults,{% if rhel8cis_rule_1_1_4_2 %}noexec,{% endif %}{% if rhel8cis_rule_1_1_4_4 %}nodev,{% endif %}{% if rhel8cis_rule_1_1_4_3 %}nosuid{% endif %}
  notify: change_requires_reboot
  with_items:
      - "{{ ansible_mounts }}"
  loop_control:
      label: "{{ item.device }}"
  when:
      - "'/var/tmp' in mount_names"
      - item.mount == "/var/tmp"
      - rhel8cis_rule_1_1_4_2 or
        rhel8cis_rule_1_1_4_3 or
        rhel8cis_rule_1_1_4_4
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - mounts
      - skip_ansible_lint
      - rule_1.1.4.2
      - rule_1.1.4.3
      - rule_1.1.4.4
